[package]
name = "rusty-chip8-emu"
version = "0.1.0"
authors = ["Anastassios Martakos <anastassios.martakos@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
