---
# hz = 0 will let the emu run as fast as possible, note that the rendering loop
# will be slower than the VM, so frame tearing is guaranteed
hz: 2048
beep_frequency: 440.0
screen_scaling: 28
rom: roms/INVADERS
log_level: WARN

general_key_mapping:
    restart_vm: R

default_key_mapping:
    Key3: 3
    Key8: 8
    Key0: 0
    C: 12
    F: 15
    Key4: 4
    Key7: 7
    B: 11
    E: 14
    A: 10
    Key9: 9
    Key1: 1
    Key2: 2
    Key5: 5
    D: 13
    Key6: 6

rom_key_mappings:
    PONG2:
        W: 1
        S: 4
        Up: 0xC
        Down: 0xD
    PONG0:
        W: 1
        S: 4
        Up: 0xC
        Down: 0xD
    BRIX:
        Left: 4
        Right: 6
    BLITZ:
        Space: 5
    INVADERS:
        Space: 5    # shoot
        A: 4        # left
        D: 6        # right
    VBRIX:
        W: 1        # up
        S: 4        # down
        Space: 7    # start
    TANK:
        Down: 2
        Left: 4
        Right: 6
        Up: 8
        Space: 5    # shoot
    TETRIS:
        Left: 5
        Right: 6
        Down: 7    # fast down
        Up: 4      # rotate
    WIPEOFF:
        Left: 4
        Right: 6
    MISSILE:
        Space: 8   # shoot
    BLINKY:
        Up: 3
        Down: 6
        Right: 8
        Left: 7

debugger:
    # Note: enabling the debugger will progressively increase memory consumption
    # Warning: do not enable this if you set hz to 0 because it will consume GBs of memory within seconds
    enable: false

    key_mapping:
        toggle_break: F1
        step_previous: F2
        step_next: F3
        print_registers: F4
        print_stack: F5
        print_timers: F6
